title: Project Bonsai Sample Playbook
logo: /assets/img/BonsaiLogo.png
description: The Bonsai Sample Project Playbook intends to provide an overview of our approach for the successful delivery of a sample project. This site aggregates best practices and resources for project scoping and delivery.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
